<div class="wrap">

	<?php
	$eddIntergration = CMMicropaymentPlatform::isEddIntegrationActive();
	$disabled        = disabled( 1, $eddIntergration, false );
	?>

	<?php if ( $eddIntergration ) : ?>
        <div class="error">
            <p>The <strong>"CM Micropayment Platform"</strong> is currently using Easy Digital Downloads Checkout mode.
                All Payment related Settings have been disabled.</p>
        </div>
	<?php endif; ?>

    <form action="" method="post">
        <table class="form-table">
            <tbody>
            <tr>
                <td colspan="2">
                    <h2><?php _e( 'Built-in PayPal' ); ?></h2>
                </td>
            </tr>

            <tr valign="top">
                <th scope="row"><?php _e( 'Use the built-in PayPal gateway?' ) ?>
                    <div class="field_help"
                         title="<?php _e( 'Enables users to buy points with the built-in PayPal gateway. Otherwise, there will be no option to purchase the points.' ) ?>"></div>
                </th>
                <td>
                    <input type="hidden" value="0" name="cm_micropayment_use_paypal">
                    <input type="checkbox" value="1" name="cm_micropayment_use_paypal"
                           id="cm_micropayment_use_paypal" <?php checked( 1, ( CMMicropaymentPlatform::get_option( 'cm_micropayment_use_paypal', 1 ) ) ); ?>>
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <h2><?php _e( 'PayPal Payments Gateway' ); ?></h2>
                </td>
            </tr>
            <tr valign="top">
                <th scope="row"><?php _e( 'Test Mode' ) ?>
                    <div class="field_help"
                         title="<?php _e( 'Allows you to test your checkout. #br# Make sure that your credentials PayPal API Credentials are connected to your PayPal sandbox account. After going to the live server, you should disable the test mode and fill the settings with your production credentials.' ) ?>"></div>
                </th>
                <td>
                    <input type="hidden" name="cm_micropayment_test_mode" value="0">
                    <input type="checkbox" <?php echo $disabled; ?> value="1" name="cm_micropayment_test_mode"
                           id="cm_micropayment_test_mode" <?php echo CMMicropaymentPlatform::get_option( 'cm_micropayment_test_mode' ) == 1 ? 'checked="checked"' : '' ?>>
                </td>
            </tr>
            <tr valign="top">
                <th scope="row">
					<?php _e( 'PayPal e-mail' ) ?>
                    <div class="field_help" title="<?php _e( 'The e-mail of your PayPal account' ); ?>"></div>
                </th>
                <td>
                    <input type="text" <?php echo $disabled; ?> name="cm_micropayment_paypal_email"
                           id="cm_micropayment_paypal_email" class="regular-text"
                           value="<?php echo CMMicropaymentPlatform::get_option( 'cm_micropayment_paypal_email', '' ); ?>">
                    <label for="cm_micropayment_paypal_email"></label>
                </td>
            </tr>
            <tr valign="top">
                <th scope="row">
					<?php _e( 'Page Style' ) ?>
                    <div class="field_help" title="<?php _e( 'The style of the PayPal page' ); ?>"></div>
                </th>
                <td>
                    <input type="text" <?php echo $disabled; ?> name="cm_micropayment_paypal_page_style"
                           id="cm_micropayment_paypal_page_style" class="regular-text"
                           value="<?php echo CMMicropaymentPlatform::get_option( 'cm_micropayment_paypal_page_style', '' ); ?>">
                    <label for="cm_micropayment_paypal_page_style"></label>
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <h2><?php _e( 'PayPal Payouts' ); ?></h2>
                </td>
            </tr>
            <tr valign="top">
                <th scope="row">
					<?php _e( 'PayPal Payout - Enabled' ) ?>
                    <div class="field_help" title="<?php _e( 'PayPal Payout - Enabled' ); ?>"></div>
                </th>
                <td>
					<?php $enabled = CMMicropaymentPlatform::get_option( 'cm_micropayment_paypal_payout_enabled', 0 ); ?>
                    <input type="hidden" name="cm_micropayment_paypal_payout_enabled" class="regular-text" value="0">
                    <input type="checkbox" name="cm_micropayment_paypal_payout_enabled"
                           id="cm_micropayment_paypal_payout_enabled" value="1" <?php checked( '1', $enabled ) ?>>
                    <label for="cm_micropayment_paypal_payout_enabled">Turn on the PayPal Payout
                        features.</label>
                </td>
            </tr>
            <tr valign="top">
                <th scope="row">
					<?php _e( 'Points to Currency ratio' ) ?>
                    <div class="field_help"
                         title="Enter how many points are worth 1 of the real currency. #br#For example, entering \'10\' means that, for each 10 points, the user gets $1"></div>
                </th>
                <td>
                    <input type="text" name="cm_micropayment_paypal_points_ratio"
                           id="cm_micropayment_paypal_points_ratio" class="regular-text"
                           value="<?php echo CMMicropaymentPlatform::get_option( 'cm_micropayment_paypal_points_ratio', '10' ); ?>">
                    <label for="cm_micropayment_paypal_points_ratio"></label>
                </td>
            </tr>
            <tr valign="top">
                <th scope="row">
                    <?php _e( 'Payment threshold' ) ?>
                    <div class="field_help"
                         title=""></div>
                </th>
                <td>
                    <input type="text" name="cm_micropayment_paypal_threshold"
                           id="cm_micropayment_paypal_threshold" class="regular-text"
                           value="<?php echo CMMicropaymentPlatform::get_option( 'cm_micropayment_paypal_threshold', '0' ); ?>">
                    <label for="cm_micropayment_paypal_threshold"></label>
                </td>
            </tr>
            <tr valign="top">
                <th scope="row">
					<?php _e( 'PayPal API - Use Test Mode?' ) ?>
                    <div class="field_help" title="<?php _e( 'PayPal API - Use Test Mode?' ); ?>"></div>
                </th>
                <td>
                    <input type="hidden" name="cm_micropayment_paypal_test_mode" class="regular-text" value="0">
                    <input type="checkbox" name="cm_micropayment_paypal_test_mode" id="cm_micropayment_paypal_test_mode"
                           value="1" <?php checked( '1', CMMicropaymentPlatform::get_option( 'cm_micropayment_paypal_test_mode', 0 ) ); ?>>
                    <label for="cm_micropayment_paypal_test_mode">Use the PayPal
                        Sandbox environment</label>
                </td>
            </tr>
            <tr valign="top">
                <th scope="row">
					<?php _e( 'Client ID' ) ?>
                    <div class="field_help" title="<?php _e( 'PayPal Client ID' ); ?>"></div>
                </th>
                <td>
                    <input type="text" name="cm_micropayment_paypal_client_id" id="cm_micropayment_paypal_client_id"
                           class="regular-text"
                           value="<?php echo CMMicropaymentPlatform::get_option( 'cm_micropayment_paypal_client_id', '' ); ?>">
                    <br>
                    <label for="cm_micropayment_paypal_client_id">Enter your PayPal Application's Client ID. Create or
                        retrieve it from the <a href="https://developer.paypal.com/developer/applications/"
                                                target="_blank">PayPal's Developer portal</a></label>
                </td>
            </tr>
            <tr valign="top">
                <th scope="row">
					<?php _e( 'Secret' ) ?>
                    <div class="field_help" title="<?php _e( 'PayPal Application Secret' ); ?>"></div>
                </th>
                <td>
                    <input type="text" name="cm_micropayment_paypal_app_secret" id="cm_micropayment_paypal_app_secret"
                           class="regular-text"
                           value="<?php echo CMMicropaymentPlatform::get_option( 'cm_micropayment_paypal_app_secret', '' ) ?>">
                    <br>
                    <label for="cm_micropayment_paypal_app_secret">Enter your PayPal Application's Secret</label>
                </td>
            </tr>
            <tr valign="top">
                <th scope="row">
					<?php _e( 'Test Client ID' ) ?>
                    <div class="field_help" title="<?php _e( 'Sandbox PayPal Application\'s Client ID.' ); ?>"></div>
                </th>
                <td>
                    <input type="text" name="cm_micropayment_paypal_test_client_id"
                           id="cm_micropayment_paypal_test_client_id" class="regular-text"
                           value="<?php echo CMMicropaymentPlatform::get_option( 'cm_micropayment_paypal_test_client_id', '' ) ?>">
                    <br>
                    <label for="cm_micropayment_paypal_test_client_id">Enter your Sandbox PayPal Application's Client
                        ID.</label>
                </td>
            </tr>
            <tr valign="top">
                <th scope="row">
					<?php _e( 'Test Secret' ) ?>
                    <div class="field_help" title="<?php _e( 'Sandbox PayPal Application\'s Secret' ); ?>"></div>
                </th>
                <td>
                    <input type="text" name="cm_micropayment_paypal_test_app_secret"
                           id="cm_micropayment_paypal_test_app_secret" class="regular-text"
                           value="<?php echo CMMicropaymentPlatform::get_option( 'cm_micropayment_paypal_test_app_secret', '' ); ?>">
                    <br>
                    <label for="cm_micropayment_paypal_test_app_secret">Enter your Sandbox PayPal Application's
                        Secret</label>
                </td>
            </tr>
            </tbody>
        </table>
        <p class="submit"><input type="submit" value="<?php _e( 'Save' ) ?>" class="button button-primary" id="submit"
                                 name="submit"></p>
    </form>
</div>