<?php
$cminds_plugin_config = array(
	'plugin-is-pro'				 => TRUE,
	'plugin-has-addons'			 => TRUE,
	'plugin-version'			 => '2.0.5',
	'plugin-abbrev'				 => 'cmmp',
	'plugin-short-slug'			 => 'micropayment',
	'plugin-addons'				 => array(
		array( 'title' => 'CM Group Operations', 'description' => 'AddOn for CM Micropayment Platform and Groups allowing to add recurring points per group and/or WordPress role.', 'link' => 'https://www.cminds.com/downloads/micropayments-group-actions/', 'link_buy' => 'https://www.cminds.com/checkout/?edd_action=add_to_cart&download_id=182304&edd_options[price_id]=1' ),
		array( 'title' => 'MicroPayments PeepSo Integration', 'description' => 'This AddOn for CM MicroPayment and PeepSo supports adding a virtual wallet functionality to PeepSo social network.', 'link' => 'https://www.cminds.com/wordpress-plugins-library/cm-micropayments-peepso-social-network-integration-addon-wordpress/#description', 'link_buy' => 'https://www.cminds.com/checkout/?edd_action=add_to_cart&download_id=149714&edd_options[price_id]=1' ),
		array( 'title' => 'MicroPayments External API', 'description' => 'This AddOn supports accessing your MicroPayments wallets using API calls from an external service. Once granted an API key an external service can add or subtract virtual currency from a user wallet using wallet id or user email', 'link' => 'https://www.cminds.com/wordpress-plugins-library/micropayments-external-api-add-wordpress/', 'link_buy' => 'https://www.cminds.com/checkout/?edd_action=add_to_cart&download_id=381605&edd_options[price_id]=1' ),
		array( 'title' => 'CM Answers', 'description' => 'Support using MicroPayment and paying with virtual currecy for posting questions and answers.', 'link' => 'https://www.cminds.com/store/answers', 'link_buy' => 'https://www.cminds.com/checkout/?edd_action=add_to_cart&download_id=1119&edd_options[price_id]=2' ),
		array( 'title' => 'CM Download Manager', 'description' => 'Support using MicroPayment and paying with virtual currecy for uploading and downloading files.', 'link' => 'https://www.cminds.com/store/downloadsmanager', 'link_buy' => 'https://www.cminds.com/checkout/?edd_action=add_to_cart&download_id=1930&edd_options[price_id]=2' ),
		array( 'title' => 'CM Video Lessons', 'description' => 'Support using MicroPayment and paying with virtual currecy for viewing video channels', 'link' => 'https://www.cminds.com/store/purchase-cm-video-lessons-manager-plugin-for-wordpress/', 'link_buy' => 'https://www.cminds.com/checkout/?edd_action=add_to_cart&download_id=31919&edd_options[price_id]=1' ),
		array( 'title' => 'CM Pay Per Post', 'description' => 'Support using MicroPayment and paying with virtual currecy for viewing individual posts or a group of posts.', 'link' => 'https://www.cminds.com/store/purchase-cm-pay-per-post-plugin-for-wordpress/', 'link_buy' => 'https://www.cminds.com/checkout/?edd_action=add_to_cart&download_id=96640&edd_options[price_id]=1' ),
	),
	'plugin-show-guide'			 => TRUE,
	'plugin-guide-text'			 => CMMicropaymentPlatform::renderPluginHelp('instructions'),
	'plugin-show-shortcodes'	 => TRUE,
	'plugin-shortcodes'			 => CMMicropaymentPlatform::renderPluginHelp('all'),
	'plugin-parent-short-slug'	 => '',
	'plugin-settings-url'		 => admin_url( 'admin.php?page=cm-micropayment-platform-settings' ),
	'plugin-file'				 => CMMP_PLUGIN_FILE,
	'plugin-dir-path'			 => plugin_dir_path( CMMP_PLUGIN_FILE ),
	'plugin-dir-url'			 => plugin_dir_url( CMMP_PLUGIN_FILE ),
	'plugin-basename'			 => plugin_basename( CMMP_PLUGIN_FILE ),
	'plugin-icon'				 => '',
	'plugin-name'				 => CMMP_NAME,
	'plugin-license-name'		 => CMMP_CANONICAL_NAME,
	'plugin-slug'				 => '',
	'plugin-menu-item'			 => CMMP_MENU_OPTION,
	'plugin-textdomain'			 => CMMP_SLUG_NAME,
	'plugin-userguide-key'		 => '198-cm-micropayments-cmmp',
	'plugin-store-url'			 => 'https://www.cminds.com/store/micropayments/',
	'plugin-review-url'			 => '',
	'plugin-changelog-url'		 => CMMP_RELEASE_NOTES,
	'plugin-licensing-aliases'	 => array( 'CM MicroPayment' ),
);
?>