<div class="wrap">

    <div id="icon-plugins" class="icon32"><br></div>
    <h2><?php _e('CM Micropayments') ?> - <?php _e('Transactions'); ?></h2>
    <ul class="subsubsub">
        <li class="all"><a<?php if(!isset($_GET['status']) || $_GET['status'] == 'all') : ?> class="current"<?php endif; ?> href="<?php echo admin_url( '/admin.php?page=cm-micropayment-platform-transactions' ); ?>">All&nbsp;<span class="count">(<?php echo $countAll ?>)</span></a> |</li>
        <li class="publish"><a<?php if(isset($_GET['status']) && $_GET['status'] == 1) : ?> class="current"<?php endif; ?> href="<?php echo admin_url( '/admin.php?page=cm-micropayment-platform-transactions&status=1' ); ?>">Completed&nbsp;<span class="count">(<?php echo $countCompleted ?>)</span></a> |</li>
        <li class="pending"><a<?php if(isset($_GET['status']) && $_GET['status'] == 0) : ?> class="current"<?php endif; ?> href="<?php echo admin_url( '/admin.php?page=cm-micropayment-platform-transactions&status=0' ); ?>">Pending&nbsp;<span class="count">(<?php echo $countPending ?>)</span></a></li>
    </ul>
    <?php
        $start_date = isset( $_GET['start-date'] )  ? sanitize_text_field( $_GET['start-date'] ) : null;
        $end_date   = isset( $_GET['end-date'] )    ? sanitize_text_field( $_GET['end-date'] )   : null;
        $status     = isset( $_GET['status'] )      ? $_GET['status'] : '';
    ?>
    <form method="get">
        <div id="payment-filters">
                <span id="payment-date-filters">
                    <label for="start-date"><?php _e( 'Start Date:' ); ?></label>
                    <input type="text" id="start-date" name="start-date" class="datepicker" value="<?php echo $start_date; ?>" placeholder="mm/dd/yyyy"/>
                    <label for="end-date"><?php _e( 'End Date:' ); ?></label>
                    <input type="text" id="end-date" name="end-date" class="datepicker" value="<?php echo $end_date; ?>" placeholder="mm/dd/yyyy"/>
                    <input type="submit" class="button-secondary" value="<?php _e( 'Apply' ); ?>"/>
                </span>
            <?php if( ! empty( $start_date ) || ! empty( $end_date ) ) : ?>
                <a href="<?php echo admin_url( '/admin.php?page=cm-micropayment-platform-transactions' ); ?>" class="button-secondary"><?php _e( 'Clear Filter' ); ?></a>
            <?php endif; ?>
        </div>
        <?php $wp_list_table->display(); ?>
        <input type="hidden" value="cm-micropayment-platform-transactions" name="page">
        <input type="hidden" name="paged" value="<?php echo (isset($_REQUEST['paged'])) ? $_REQUEST['paged'] : '' ?>"/>
    </form>


</div>

<script>
    jQuery(document).ready(function(){
       jQuery('.datepicker').datepicker();
    });
</script>
